= Writing an InfoQ Mini-Book with Asciidoctor

An Asciidoctor-powered presentation that shows you how to write an http://www.infoq.com/minibooks/[InfoQ Mini-Book] with
http://asciidoctor.org/[Asciidoctor].

http://mraible.github.io/infoq-mini-book-presentation/[Slides] | https://www.youtube.com/watch?v=mVFr3RzBPu8[Presentation on YouTube]

If you'd like to create a similar presentation, clone https://github.com/opendevise/bespoke-emulating-shower[Bespoke.js Emulating Shower].

== Building the presentation

=== Prerequisites

Ensure you have the following installed on your machine:

. https://www.ruby-lang.org[Ruby] 2.x footnote:[We strongly recommend using http://rvm.io[RVM] to manage Ruby.]
. http://bundler.io[Bundler]

 $ gem install bundler

. https://nodejs.org[Node.js] footnote:[We strongly recommend using https://github.com/creationix/nvm[nvm] to manage Node.]
. http://gulpjs.com[Gulp]

 $ npm install -g gulp

=== Setup

Then, install the required dependencies:

 $ bundle && npm install

Now you're all set to build the presentation!

=== Building the static version

You can build a static version of the slides using the following command:

 $ gulp

The files are built into the _dist_ directory.
You can then view the slides by navigating to _dist/index.html_ in your browser.

=== Launching the preview server

The preview server will monitor files for changes and automatically update the presentation.
You can launch the preview server using:

 $ gulp serve

Once the server is running, you can view the slides by navigating to \http://localhost:8000 in your browser.

=== Deploy static version

You can publish to GitHub pages by running the following command:

  $ gulp deploy
  
=== Tips and Tricks

A few tips from https://github.com/mojavelinux[Dan Allen]:

1. If you don't want it the presentation to start in overview, drop the `autostart: true` option from the `overview()` plugin call in `src/scripts/main.js`.
2. If you want builds to work each time you visit the slide, remove https://github.com/mraible/infoq-mini-book-presentation/blob/master/src/scripts/main.js#L27-L41[this function].
3. You can export the presentation to PDF using https://github.com/astefanutti/decktape[DeckTape].
